### PR TITLE
Deprecate items that got integrated into `core`

### LINKED ISSUE #7: Obsoletion of features that were integrated into `core`
First off, let me say thank you so very much for creating this small crate. It helps tremendously at several of my embedded projects; primarily so I only have to write implementations once for async and then get the blocking version for free.

That said, there are a couple of items in the crate that might be worth deprecating, so people realize those are now in the `core` library:

- [`cassette::pin_mut`](https://docs.rs/cassette/latest/cassette/macro.pin_mut.html) -> [`core::pin::pin`](https://doc.rust-lang.org/core/pin/macro.pin.html) (Rust `1.68.0`)
- [`cassette::futures::poll_fn`](https://docs.rs/cassette/latest/cassette/futures/fn.poll_fn.html) -> [`core::future::poll_fn`](https://doc.rust-lang.org/core/future/fn.poll_fn.html) (Rust `1.64.0`)
- [`cassette::futures::PollFn`](https://docs.rs/cassette/latest/cassette/futures/struct.PollFn.html) -> [`core::future::PollFn`](https://doc.rust-lang.org/core/future/struct.PollFn.html) (Rust `1.64.0`)

Again, thanks :)
Fyi, now with the release of [`embedded-hal 1.0`](https://docs.rs/embedded-hal/1.0.0-rc.1/embedded_hal/index.html) and [`embedded-hal-async 1.0`](https://docs.rs/embedded-hal-async/1.0.0-rc.1/embedded_hal_async/) your crate might experience some exposure, as it fits that usecase perfectly ;) especially with the stabilization of `async-traits` next month.

### PR DESCRIPTION
**Pull request by Finomnis**
Closes #7

### CODE REVIEW

**Comment by Finomnis** [comment]
@jamesmunns I at least assume that this crate is still maintained, I know it hasn't been updated since 2021, but it's simple and polished enough that it shouldn't require updates :D and I saw you are still active in other projects.

**Comment by jamesmunns** [comment]
Thanks for the ping! I'll cut a release, but admit that this crate is not particuarly still maintained.

**Comment by jamesmunns** [comment]
@Finomnis released +tagged as v0.2.4

**Comment by Finomnis** [comment]
> Thanks for the ping! I'll cut a release, but admit that this crate is not particuarly still maintained.

It doesn't have to be, it's stable and useful :)

**Pull request merged**
