### PR TITLE
Cleanup, polish and bump to `0.3.0`

### PR DESCRIPTION
**Pull request by Finomnis**
- Remove obsolete `futures` mod
- Add CI
- Adjust licenses to `MIT` and `Apache 2.0`, as [recommended](https://rust-lang.github.io/api-guidelines/necessities.html#:~:text=Besides%20the%20dual%20MIT%2FApache,restrictions%20of%20Rust's%20MIT%20license.).
- Add MSRV
- Add tags
- Bump to `0.3.0`

This is on top of #9.

### CODE REVIEW

**Comment by Finomnis** [comment]
@jamesmunns I'm not entirely sure why the CI doesn't run, might be setting in the repository?

**Comment by Finomnis** [comment]
@jamesmunns Also you mentioned that this crate is not really maintained; if you want I can become a co-maintainer. Although I don't think there will be much activity after this.

**Comment by jamesmunns** [comment]
@Finomnis added you as a collaborator and invited you as a crate owner. Please feel free to make a 0.3/1.0 release.

**Comment by Finomnis** [comment]
> @Finomnis added you as a collaborator and invited you as a crate owner. Please feel free to make a 0.3/1.0 release.

Cool! Thanks. I'll try my best to serve you and this crate well.

**Pull request merged**
